[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d6d812c79bb1f845c31c2696ba356ed0f93b3b4"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "7829884629e59edd8ba9286e60b3bb372b5bc17376de49e77860612c67bcb906"
    url = "https://github.com/barche/libjulia_jll.jl/releases/download/libjulia-v1.6.0+1/libjulia.v1.6.0.x86_64-linux-gnu-cxx11.tar.gz"
